Repository VKCOM/admstorm, pull requests merged in 2022-08, with the labels that each got.

#170 added a check for reserved response code
  src/main/kotlin/com/vk/admstorm/CommandRunner.kt
Labels: refactoring

#169 renamed icons class
  src/main/kotlin/com/vk/admstorm/actions/KphpPlaygroundAction.kt
  src/main/kotlin/com/vk/admstorm/actions/PlaygroundFromSelectionAction.kt
  src/main/kotlin/com/vk/admstorm/actions/SendLogsToSentryAction.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchKphpConfigurationType.kt
  src/main/kotlin/com/vk/admstorm/configuration/kphp/KphpConfigurationType.kt
  src/main/kotlin/com/vk/admstorm/configuration/phplinter/PhpLinterConfigurationType.kt
  src/main/kotlin/com/vk/admstorm/configuration/yarnwatch/YarnWatchConfigurationType.kt
  src/main/kotlin/com/vk/admstorm/executors/KphpComplexRunExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/KphpRunExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/KphpScriptExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/PhpLinterExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/WatchDebugLogCommandExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/WatchDebugLogExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/YarnWatchCommandExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/YarnWatchExecutor.kt
  src/main/kotlin/com/vk/admstorm/ui/AdmIcons.kt
  src/main/kotlin/com/vk/admstorm/ui/MyIcons.kt
  src/main/kotlin/com/vk/admstorm/ui/WatchDebugLogStatusBarWidget.kt
  src/main/kotlin/com/vk/admstorm/ui/YarnWatchStatusBarWidget.kt
Labels: refactoring

#173 added service list
  src/main/kotlin/com/vk/admstorm/env/Env.kt
  src/main/kotlin/com/vk/admstorm/env/EnvListener.kt
  src/main/kotlin/com/vk/admstorm/ui/AdmIcons.kt
  src/main/kotlin/com/vk/admstorm/ui/ServiceListToolWindow.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/icons/sentry.svg
  src/main/resources/icons/service/confluence.svg
  src/main/resources/icons/service/default.svg
  src/main/resources/icons/service/gitlab.svg
  src/main/resources/icons/service/grafana.svg
  src/main/resources/icons/service/jira.svg
  src/main/resources/icons/service/pmcmanager.svg
  src/main/resources/icons/service/sentry.svg
  src/main/resources/icons/service/teamcity.svg
  src/main/resources/icons/services.svg
Labels: enhancement

#172 updated versions
  build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: refactoring

#176 added timeout code
  src/main/kotlin/com/vk/admstorm/CommandRunner.kt
Labels: refactoring

#178 fixed exception about `GitBranchUtils.getCurrentRepository()`
  build.gradle.kts
  gradle.properties
  src/main/kotlin/com/vk/admstorm/actions/DeployTestDomainAction.kt
  src/main/kotlin/com/vk/admstorm/actions/git/PushOptionsDialog.kt
  src/main/kotlin/com/vk/admstorm/actions/git/PushToGitlabAction.kt
  src/main/kotlin/com/vk/admstorm/git/GitUtils.kt
  src/main/kotlin/com/vk/admstorm/git/sync/SyncChecker.kt
  src/main/kotlin/com/vk/admstorm/git/sync/branches/RemoteBranchSwitcher.kt
  src/main/kotlin/com/vk/admstorm/git/sync/commits/NotSyncCommitsDialog.kt
  src/main/kotlin/com/vk/admstorm/git/sync/files/GitStatus.kt
  src/main/kotlin/com/vk/admstorm/utils/MyUtils.kt
Labels: small fix

#179 v1.3.2
  CHANGELOG.md
  docs/whatsnew.html
  gradle.properties
  src/main/resources/META-INF/plugin.xml
Labels: enhancement
