Repository VKCOM/admstorm, pull requests merged in 2022-06, with the labels that each got.

#77 Fix getting opensc path in Linux
  src/main/kotlin/com/vk/admstorm/ssh/YubikeyHandler.kt
Labels: bug

#79 Added tab implementation
  docs/css/index.css
  docs/css/index.css.map
  docs/css/index.scss
  docs/install.html
  docs/js/script.js
Labels: documentation

#86 added a custom logger
  src/main/kotlin/com/vk/admstorm/AdmStormStartupActivity.kt
  src/main/kotlin/com/vk/admstorm/diagnostic/AdmStormLogger.kt
  src/main/kotlin/com/vk/admstorm/diagnostic/AdmStormLoggerFactory.kt
Labels: enhancement

#88 added recognize of Jira tickets in PHPDoc, JSDoc, and CSS comments
  CHANGELOG.md
  gradle.properties
  src/main/kotlin/com/vk/admstorm/env/Env.kt
  src/main/kotlin/com/vk/admstorm/psi/references/JiraReferenceContributor.kt
  src/main/resources/META-INF/plugin.xml
Labels: enhancement

#84 added sending errors to Sentry
  CHANGELOG.md
  build.gradle.kts
  src/main/kotlin/com/vk/admstorm/AdmStormStartupActivity.kt
  src/main/kotlin/com/vk/admstorm/diagnostic/AdmStormLogger.kt
  src/main/kotlin/com/vk/admstorm/diagnostic/AdmStormLoggerFactory.kt
  src/main/kotlin/com/vk/admstorm/diagnostic/SentryErrorReporter.kt
  src/main/kotlin/com/vk/admstorm/git/GitUtils.kt
  src/main/kotlin/com/vk/admstorm/notifications/AdmNotification.kt
  src/main/kotlin/com/vk/admstorm/services/ConfigService.kt
  src/main/kotlin/com/vk/admstorm/services/SentryService.kt
  src/main/kotlin/com/vk/admstorm/settings/AdmStormSettingsConfigurable.kt
  src/main/kotlin/com/vk/admstorm/settings/AdmStormSettingsState.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/plugin_config.json
Labels: enhancement

#92 fixed a problem with opening SSH tunnels
  CHANGELOG.md
  src/main/kotlin/com/vk/admstorm/utils/MyUtils.kt
  src/main/kotlin/com/vk/admstorm/utils/PhpDebugUtils.kt
Labels: bug

#96 added disabling error sending in Sentry
  build.gradle.kts
  src/main/kotlin/com/vk/admstorm/services/SentryService.kt
Labels: enhancement

#99 treat benchmark classes and methods as always implicit used
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchImplicitTypeProvider.kt
  src/main/resources/META-INF/plugin.xml
Labels: enhancement

#97 added a welcome message for each plugin update
  CHANGELOG.md
  src/main/kotlin/com/vk/admstorm/AdmStormStartupActivity.kt
  src/main/kotlin/com/vk/admstorm/notifications/AdmNotification.kt
Labels: enhancement

#106 fixed password saving when reset yubikey
  src/main/kotlin/com/vk/admstorm/ssh/YubikeyHandler.kt
Labels: small fix

#104 debug log: fixed bug when updating the size in the call, the size in the link was not updated
  src/main/kotlin/com/vk/admstorm/highlight/DebugLogLineMarkerProvider.kt
Labels: small fix

#95 added packages tests support
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/PackagesTestUtils.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/PhpUnitScope.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfiguration.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationEditor.form
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationEditor.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationOptions.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationProducer.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationRunState.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitRerunFailedTestsAction.kt
  src/main/kotlin/com/vk/admstorm/utils/MyPathUtils.kt
  src/main/kotlin/com/vk/admstorm/utils/MyUtils.kt
Labels: enhancement

#91 v1.3.0
  CHANGELOG.md
  docs/faq.html
  docs/index.html
  docs/whatsnew.html
  gradle.properties
  src/main/resources/META-INF/plugin.xml
Labels: enhancement

#108 added message for sentry reports and changed several log types
  src/main/kotlin/com/vk/admstorm/diagnostic/AdmStormLogger.kt
  src/main/kotlin/com/vk/admstorm/diagnostic/SentryErrorReporter.kt
  src/main/kotlin/com/vk/admstorm/git/sync/SyncChecker.kt
  src/main/kotlin/com/vk/admstorm/git/sync/files/RemoteFileManager.kt
  src/main/kotlin/com/vk/admstorm/playground/KphpPlaygroundWindow.kt
  src/main/kotlin/com/vk/admstorm/services/SentryService.kt
  src/main/kotlin/com/vk/admstorm/ssh/LostConnectionHandler.kt
  src/main/kotlin/com/vk/admstorm/ssh/SshConnectionService.kt
  src/main/kotlin/com/vk/admstorm/transfer/TransferService.kt
  src/main/kotlin/com/vk/admstorm/utils/MyUtils.kt
Labels: small fix

#109 replaced old `Logger.getInstance(...)` with `logger<...>()`
  src/main/kotlin/com/vk/admstorm/CommandRunner.kt
  src/main/kotlin/com/vk/admstorm/actions/ShowKphpSourcesAction.kt
  src/main/kotlin/com/vk/admstorm/actions/git/PushOptionsDialog.kt
  src/main/kotlin/com/vk/admstorm/actions/git/PushToGitlabAction.kt
  src/main/kotlin/com/vk/admstorm/actions/git/panels/changes/GitLazyContentRevision.kt
  src/main/kotlin/com/vk/admstorm/env/Env.kt
  src/main/kotlin/com/vk/admstorm/git/AdmBranchContextTracker.kt
  src/main/kotlin/com/vk/admstorm/git/sync/SyncChecker.kt
  src/main/kotlin/com/vk/admstorm/git/sync/branches/LocalBranchSwitcher.kt
  src/main/kotlin/com/vk/admstorm/git/sync/branches/RemoteBranchSwitcher.kt
  src/main/kotlin/com/vk/admstorm/git/sync/conflicts/ConflictDialog.kt
  src/main/kotlin/com/vk/admstorm/git/sync/files/GitStatus.kt
  src/main/kotlin/com/vk/admstorm/git/sync/files/RemoteFile.kt
  src/main/kotlin/com/vk/admstorm/notifications/AdmNotification.kt
  src/main/kotlin/com/vk/admstorm/ssh/LostConnectionHandler.kt
  src/main/kotlin/com/vk/admstorm/ssh/RemoteDataProducerWrapper.kt
  src/main/kotlin/com/vk/admstorm/ssh/SshConnectionService.kt
  src/main/kotlin/com/vk/admstorm/transfer/TransferService.kt
  src/main/kotlin/com/vk/admstorm/ui/MessageDialog.kt
Labels: refactoring

#111 fixed api tests
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationProducer.kt
Labels: small fix

#112 removed unnecessary logging when it wasn't possible to find a group
  src/main/kotlin/com/vk/admstorm/actions/git/listeners/PatternBasedProgressListener.kt
Labels: small fix, sentry

#114 various refactor
  src/main/kotlin/com/vk/admstorm/AdmService.kt
  src/main/kotlin/com/vk/admstorm/actions/AdmActionsGroup.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchBaseConfigurationProducer.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationEditor.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationLineMarkerProvider.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationRunState.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchImplicitTypeProvider.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchUtils.kt
  src/main/kotlin/com/vk/admstorm/configuration/kphp/KphpScriptRunner.kt
  src/main/kotlin/com/vk/admstorm/configuration/kphp/KphpUtils.kt
  src/main/kotlin/com/vk/admstorm/configuration/php/PhpDebugUtils.kt
  src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfigurationRunState.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationProducer.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationRunState.kt
  src/main/kotlin/com/vk/admstorm/executors/KphpScriptExecutor.kt
  src/main/kotlin/com/vk/admstorm/playground/KphpPlaygroundWindow.kt
  src/main/kotlin/com/vk/admstorm/psi/references/JiraReferenceContributor.kt
  src/main/kotlin/com/vk/admstorm/ssh/YubikeyHandler.kt
  src/main/kotlin/com/vk/admstorm/transfer/Transfer.kt
  src/main/kotlin/com/vk/admstorm/utils/MyPathUtils.kt
  src/main/kotlin/com/vk/admstorm/utils/MySshUtils.kt
Labels: refactoring

#117 hid yarn watch for non-vkcom projects
  src/main/kotlin/com/vk/admstorm/ui/YarnWatchStatusBarWidget.kt
  src/main/kotlin/com/vk/admstorm/ui/YarnWatchStatusBarWidgetFactory.kt
Labels: small fix

#119 fixed a performance issue for debug log line marker
  src/main/kotlin/com/vk/admstorm/highlight/DebugLogLineMarkerProvider.kt
Labels: small fix

#121 added clarification about the project root
  docs/css/index.css
  docs/css/index.scss
  docs/install.html
Labels: documentation

#123 updated install page
  docs/images/settings.png
  docs/install.html
Labels: documentation

#115 function for getting the current Git user now returns local data
  src/main/kotlin/com/vk/admstorm/git/GitUtils.kt
  src/main/kotlin/com/vk/admstorm/services/SentryService.kt
Labels: small fix, sentry

#127 refactor `BaseRunnableExecutor`
  src/main/kotlin/com/vk/admstorm/actions/ActionToolbarFastEnableAction.kt
  src/main/kotlin/com/vk/admstorm/actions/SimpleToolbarAction.kt
  src/main/kotlin/com/vk/admstorm/configuration/kphp/KphpConfigurationRunState.kt
  src/main/kotlin/com/vk/admstorm/executors/ActionToolbarPanel.kt
  src/main/kotlin/com/vk/admstorm/executors/BaseRemoteExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/BaseRunnableExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/BuildersExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/DeployTestDomainExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/KphpComplexRunExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/KphpRunExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/KphpScriptExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/PhpLinterExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/PushToRemoteExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/RemotePhpRunExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/RunAnythingExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/YarnWatchCommandExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/tabs/BaseTab.kt
  src/main/kotlin/com/vk/admstorm/executors/tabs/ConsoleTab.kt
  src/main/kotlin/com/vk/admstorm/executors/tabs/DiffTab.kt
  src/main/kotlin/com/vk/admstorm/executors/tabs/ProblemsTab.kt
  src/main/kotlin/com/vk/admstorm/executors/tabs/Tab.kt
  src/main/kotlin/com/vk/admstorm/playground/KphpPlaygroundWindow.kt
  src/main/kotlin/com/vk/admstorm/services/DeployTestDomainService.kt
  src/main/kotlin/com/vk/admstorm/services/YarnWatchService.kt
Labels: refactoring, small fix

#131 fixed exception after automatically opening an SSH tunnel
  src/main/kotlin/com/vk/admstorm/configuration/php/PhpDebugUtils.kt
Labels: bug

#132 fixed run PHPUnit tests via context menu for a file
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationProducer.kt
Labels: small fix

#134 added run ktest benchmarks via a context menu for a file
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchBaseConfigurationProducer.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchImplicitUsageProvider.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchUtils.kt
  src/main/resources/META-INF/plugin.xml
Labels: small fix

#135 fixed ktest benchmarks a method filter regexp
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationRunState.kt
Labels: small fix

#137 fixed freeze when run ktest benchmarks
  src/main/kotlin/com/vk/admstorm/configuration/WithSshConfiguration.kt
  src/main/kotlin/com/vk/admstorm/configuration/WithSshConfigurationRunner.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationRunState.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationRunner.kt
  src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfiguration.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfiguration.kt
  src/main/kotlin/com/vk/admstorm/configuration/runanything/RunAnythingConfiguration.kt
  src/main/resources/META-INF/plugin.xml
Labels: small fix

#142 updated api tests
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationProducer.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationRunState.kt
Labels: small fix

#147 fixed a freeze when connection is lost and bug when mark yarn watch as running when connection is lost
  src/main/kotlin/com/vk/admstorm/actions/CreateHasteAction.kt
  src/main/kotlin/com/vk/admstorm/configuration/WithSshConfigurationRunner.kt
  src/main/kotlin/com/vk/admstorm/configuration/builders/BuildersConfigurationRunState.kt
  src/main/kotlin/com/vk/admstorm/configuration/kphp/KphpConfigurationRunState.kt
  src/main/kotlin/com/vk/admstorm/configuration/kphp/KphpScriptRunner.kt
  src/main/kotlin/com/vk/admstorm/configuration/phplinter/PhpLinterConfigurationRunState.kt
  src/main/kotlin/com/vk/admstorm/executors/BaseRemoteExecutor.kt
  src/main/kotlin/com/vk/admstorm/executors/KphpScriptExecutor.kt
  src/main/kotlin/com/vk/admstorm/git/sync/files/RemoteFileManager.kt
  src/main/kotlin/com/vk/admstorm/playground/KphpPlaygroundWindow.kt
  src/main/kotlin/com/vk/admstorm/services/RunAnythingOnServerService.kt
  src/main/kotlin/com/vk/admstorm/services/YarnWatchService.kt
  src/main/kotlin/com/vk/admstorm/transfer/TransferService.kt
  src/main/kotlin/com/vk/admstorm/utils/MySshUtils.kt
  src/main/kotlin/com/vk/admstorm/utils/MyUtils.kt
Labels: small fix

#154 added checking of new plugin version
  src/main/kotlin/com/vk/admstorm/AdmService.kt
  src/main/kotlin/com/vk/admstorm/AdmStormStartupActivity.kt
  src/main/kotlin/com/vk/admstorm/diagnostic/AdmStormLoggerFactory.kt
  src/main/kotlin/com/vk/admstorm/services/SentryService.kt
Labels: enhancement

#138 v1.3.1
  CHANGELOG.md
  docs/images/watch_debug_log.png
  docs/whatsnew.html
  gradle.properties
  src/main/kotlin/com/vk/admstorm/ssh/SshConnectionService.kt
Labels: enhancement
