Repository VKCOM/admstorm, pull requests merged in 2023-12, with the labels that each got.

#214 replaced deprecated `Kotlin UI DSL` methods
  docs/index.html
  src/main/kotlin/com/vk/admstorm/actions/DeployTestDomainAction.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationEditor.kt
  src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationRunState.kt
  src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationEditor.kt
  src/main/kotlin/com/vk/admstorm/git/sync/branches/SyncBranchesDialog.kt
  src/main/kotlin/com/vk/admstorm/git/sync/files/FilesNotSyncDialog.kt
  src/main/kotlin/com/vk/admstorm/highlight/markers/impl/MarkerService.kt
  src/main/kotlin/com/vk/admstorm/ssh/EnterPasswordDialog.kt
  src/main/kotlin/com/vk/admstorm/ui/ServiceListToolWindow.kt
Labels: refactoring

#218 disabled sending errors in development mode
  src/main/kotlin/com/vk/admstorm/services/SentryService.kt
Labels: refactoring, small fix, sentry

#216 removed implicit dependency from markers
  src/main/kotlin/com/vk/admstorm/env/Env.kt
  src/main/kotlin/com/vk/admstorm/highlight/markers/admmarker/ABMarker.kt
  src/main/kotlin/com/vk/admstorm/highlight/markers/admmarker/BufferMarker.kt
  src/main/kotlin/com/vk/admstorm/highlight/markers/admmarker/LoggerMarker.kt
  src/main/kotlin/com/vk/admstorm/highlight/markers/admmarker/StatshouseMarker.kt
  src/main/kotlin/com/vk/admstorm/highlight/markers/impl/MarkerBrowser.kt
Labels: refactoring

#215 added highlighting `Jira` links
  src/main/kotlin/com/vk/admstorm/AdmStartupService.kt
Labels: enhancement
