Repository VKCOM/admstorm, pull requests merged in 2024-02, with the labels that each got.

#223 sending `Hastebin` through HTTP request
  src/main/kotlin/com/vk/admstorm/actions/CreateHasteAction.kt
  src/main/kotlin/com/vk/admstorm/actions/SendLogsToHastebinAction.kt
  src/main/kotlin/com/vk/admstorm/executors/BaseRemoteExecutor.kt
  src/main/kotlin/com/vk/admstorm/playground/KphpPlaygroundWindow.kt
  src/main/kotlin/com/vk/admstorm/services/HastebinService.kt
Labels: refactoring

#224 ssh configuration changes notification
  src/main/kotlin/com/vk/admstorm/AdmStormStartupActivity.kt
  src/main/kotlin/com/vk/admstorm/startup/ChangeSshBackendStartup.kt
Labels: enhancement

#219 additional information in logs
  src/main/kotlin/com/vk/admstorm/utils/MyUtils.kt
Labels: enhancement

#207 notifications about new versions of plugins
  src/main/kotlin/com/vk/admstorm/AdmStormStartupActivity.kt
  src/main/kotlin/com/vk/admstorm/startup/PluginsUpdateStartup.kt
Labels: enhancement

#225 fixed checking for new versions of plugins
  src/main/kotlin/com/vk/admstorm/AdmStormStartupActivity.kt
  src/main/kotlin/com/vk/admstorm/startup/PluginsUpdateStartup.kt
Labels: bug

#221 version 2.0.3 for PhpStorm 2023.3
  .github/workflows/build.yml
  CHANGELOG.md
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  settings.gradle.kts
  src/main/kotlin/com/vk/admstorm/utils/MyUtils.kt
Labels: enhancement
