Repository VKCOM/admstorm, pull requests merged in 2025-07, with the labels that each got.

#242 added possibility to specify custom path to `OpenSC` provider
  src/main/kotlin/com/vk/admstorm/settings/AdmStormSettingsConfigurable.kt
  src/main/kotlin/com/vk/admstorm/settings/AdmStormSettingsState.kt
  src/main/kotlin/com/vk/admstorm/ssh/OpenSCProviderDetector.kt
  src/main/kotlin/com/vk/admstorm/ssh/OpenSCProviderManager.kt
  src/main/kotlin/com/vk/admstorm/ssh/YubikeyHandler.kt
Labels: enhancement

#238 fix: exception with failing to open SSH channel with no yubikey key
  src/main/kotlin/com/vk/admstorm/ssh/SshConnectionService.kt
Labels: bug

#245 version 2.0.8 for PhpStorm 2024.3
  CHANGELOG.md
  gradle.properties
  ignored-problems.txt
Labels: plugin update
